### PR TITLE
add enrichment to standardize src/dst

### PR DESCRIPTION
**Pull request by anubisg1**
according to ECS, server = destination and client = sourc

### CODE REVIEW

**Comment by brian-grabau** [comment]
# according to ECS, server = destination and client = source = correct that is why we never use server or client in any of our parsing as it is redundant.

**Comment by brian-grabau** [comment]
Would this be needed if we do not use server or client? I like ECS but this is one issue I have, already too many fields and additional are needed and Kibana has a limit of 1024 fields. Recommendation was to have different patterns for different data types but then you cannot search across all indexes defeating the purpose of having a consistent schema.

**Comment by KrishnanandSingh** [comment]
@anubisg1 thoughts?

**Comment by anubisg1** [comment]
server/client are application concepts , while source/destination are more network concepts.

Server/Client makes sense only if you pull data from , or correlate network data with server/application logs

**Comment by anubisg1** [comment]
another way of looking at it, is what elastiflow does

image

**Pull request closed without merging**
